Repository purrplingcat/NpcAdventures, pull requests merged in 2019-11, with the labels that each got.

#41 Contributions/smirkii/fight bubbles
  NpcAdventure/assets/Dialogue/AbigailSpouse.json
  NpcAdventure/assets/Strings/SpeechBubbles.json
Labels: content

#29 Support for fight speech bubbles
  NpcAdventure/AI/AI_StateMachine.cs
  NpcAdventure/AI/Controller/FightController.cs
  NpcAdventure/StateMachine/State/RecruitedState.cs
  NpcAdventure/Utils/DialogueHelper.cs
  NpcAdventure/assets/Dialogue/AbigailSpouse.json
  NpcAdventure/assets/Strings/SpeechBubbles.json
Labels: content, feature

#36 Idle mode: Animate behavior
  NpcAdventure/AI/AI_StateMachine.cs
  NpcAdventure/AI/Controller/FightController.cs
  NpcAdventure/AI/Controller/FollowController.cs
  NpcAdventure/AI/Controller/IdleController.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/NpcAdventureMod.cs
  NpcAdventure/StateMachine/State/RecruitedState.cs
  NpcAdventure/Utils/DialogueHelper.generator.cs
  NpcAdventure/Utils/Extensions.cs
  NpcAdventure/assets/Data/IdleBehaviors.json
  NpcAdventure/assets/Data/IdleNPCDefinitions.json
  NpcAdventure/assets/Data/animationDescriptions.json
Labels: content, feature

#49 Fix harmony patcher for android, linux and mac
  NpcAdventure/NpcAdventureMod.cs
  NpcAdventure/Patches/GameLocationDrawPatch.cs
Labels: bugfix

#51 Fixed NPC stuck in bench, chair or couch when recruited
  NpcAdventure/StateMachine/CompanionStateMachine.cs
Labels: bug, bugfix

#50 Support for localisations and content packs
  NpcAdventure/CompanionManager.cs
  NpcAdventure/Driver/StuffDriver.cs
  NpcAdventure/Loader/AssetsManager.cs
  NpcAdventure/Loader/ContentLoader.cs
  NpcAdventure/Loader/ContentPacks/AssetPatch.cs
  NpcAdventure/Loader/ContentPacks/ContentPackProvider.cs
  NpcAdventure/Loader/ContentPacks/ManagedContentPack.cs
  NpcAdventure/Loader/IContentLoader.cs
  NpcAdventure/Model/ContentPackData.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/NpcAdventureMod.cs
  NpcAdventure/Utils/Helper.cs
  NpcAdventure/assets/Data/CompanionDispositions.json
Labels: content, feature, technical

#56 User configuration
  NpcAdventure/CompanionManager.cs
  NpcAdventure/Model/Config.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/NpcAdventureMod.cs
  NpcAdventure/StateMachine/State/AvailableState.cs
  NpcAdventure/StateMachine/State/RecruitedState.cs
Labels: content, feature

#52 Feature/portugal translation
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/assets/Dialogue/Abigail.pt-BR.json
  NpcAdventure/assets/Dialogue/AbigailSpouse.pt-BR.json
  NpcAdventure/assets/Dialogue/Alex.pt-BR.json
  NpcAdventure/assets/Dialogue/Elliott.pt-BR.json
  NpcAdventure/assets/Dialogue/Emily.pt-BR.json
  NpcAdventure/assets/Dialogue/Haley.pt-BR.json
  NpcAdventure/assets/Dialogue/Harvey.pt-BR.json
  NpcAdventure/assets/Dialogue/Leah.pt-BR.json
  NpcAdventure/assets/Dialogue/Maru.pt-BR.json
  NpcAdventure/assets/Dialogue/Penny.pt-BR.json
  NpcAdventure/assets/Dialogue/Sam.pt-BR.json
  NpcAdventure/assets/Dialogue/Sebastian.pt-BR.json
  NpcAdventure/assets/Dialogue/Shane.pt-BR.json
  NpcAdventure/assets/Strings/SpeechBubbles.pt-BR.json
  NpcAdventure/assets/Strings/Strings.pt-BR.json
Labels: content

#55 Added harmony and fixed sword swing animation
  NpcAdventure/AI/AI_StateMachine.cs
  NpcAdventure/AI/Controller/FightController.cs
  NpcAdventure/CompanionManager.cs
  NpcAdventure/Events/ISpecialModEvents.cs
  NpcAdventure/Events/SpecialModEvents.cs
  NpcAdventure/Internal/IDrawable.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/NpcAdventureMod.cs
  NpcAdventure/Patches/GameLocationDrawPatch.cs
  NpcAdventure/StateMachine/State/RecruitedState.cs
  NpcAdventure/packages.config
Labels: bugfix, feature
