Repository purrplingcat/NpcAdventures, pull requests merged in 2019-10, with the labels that each got.

#8 Added new basic dialogues
  PurrplingMod/assets/Dialogue/Abigail.json
  PurrplingMod/assets/Dialogue/Alex.json
  PurrplingMod/assets/Dialogue/Elliott.json
  PurrplingMod/assets/Dialogue/Emily.json
  PurrplingMod/assets/Dialogue/Haley.json
  PurrplingMod/assets/Dialogue/Harvey.json
  PurrplingMod/assets/Dialogue/Leah.json
  PurrplingMod/assets/Dialogue/Maru.json
  PurrplingMod/assets/Dialogue/Penny.json
  PurrplingMod/assets/Dialogue/Sam.json
  PurrplingMod/assets/Dialogue/Sebastian.json
  PurrplingMod/assets/Dialogue/Shane.json
  README.md
Labels: content, planned

#25 Fix/penny animation
  NpcAdventure/PurrplingMod.cs
  NpcAdventure/StateMachine/State/AvailableState.cs
  NpcAdventure/StateMachine/State/RecruitedState.cs
Labels: bugfix, testing

#17 Fighting with swords
  NpcAdventure/AI/AI_StateMachine.cs
  NpcAdventure/AI/Controller/FightController.cs
  NpcAdventure/AI/Controller/FollowController.cs
  NpcAdventure/AI/Controller/IController.cs
  NpcAdventure/AI/Controller/PathFinder.cs
  NpcAdventure/AI/EventArgsLocationChanged.cs
  NpcAdventure/Buffs/BuffManager.cs
  NpcAdventure/CompanionManager.cs
  NpcAdventure/Driver/DialogueDriver.cs
  NpcAdventure/Driver/HintDriver.cs
  NpcAdventure/Driver/StuffDriver.cs
  NpcAdventure/Internal/IUpdateable.cs
  NpcAdventure/Loader/ContentLoader.cs
  NpcAdventure/Loader/IContentLoader.cs
  NpcAdventure/Model/BagDumpInfo.cs
  NpcAdventure/Model/BuffInfo.cs
  NpcAdventure/Model/CompanionMetaData.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/NpcAdventureMod.cs
  NpcAdventure/Objects/Package.cs
  NpcAdventure/StateMachine/CompanionState.cs
  NpcAdventure/StateMachine/CompanionStateMachine.cs
  NpcAdventure/StateMachine/State/AvailableState.cs
  NpcAdventure/StateMachine/State/RecruitedState.cs
  NpcAdventure/StateMachine/State/ResetState.cs
  NpcAdventure/StateMachine/State/UnavailableState.cs
  NpcAdventure/StateMachine/StateFeatures/ICompanionIntegrator.cs
  NpcAdventure/StateMachine/StateFeatures/IDialogueDetector.cs
  NpcAdventure/StateMachine/StateFeatures/IRequestedDialogueCreator.cs
  NpcAdventure/Utils/DialogueHelper.VariousKeyGenerator.cs
  NpcAdventure/Utils/DialogueHelper.cs
  NpcAdventure/Utils/Helper.cs
  NpcAdventure/Utils/Helper/DrawDuringUse.cs
  NpcAdventure/assets/CompanionDispositions.json
Labels: feature

#11 Fix English a bit
  NpcAdventure/assets/Buffs/Abigail.json
  NpcAdventure/assets/Dialogue/Abigail.json
  NpcAdventure/assets/Strings/SpeechBubbles.json
  NpcAdventure/assets/Strings/Strings.json
Labels: content

#28 Removed impossible Abby's buffs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/StateMachine/State/RecruitedState.cs
  NpcAdventure/assets/Buffs/Abigail.json
Labels: content, feature
