Repository purrplingcat/NpcAdventures, pull requests merged in 2020-02, with the labels that each got.

#89 Support for non-string dictionary assets and locaizations for ContentPacks
  NpcAdventure/Loader/AssetPatchHelper.cs
  NpcAdventure/Loader/AssetsManager.cs
  NpcAdventure/Loader/ContentPacks/AssetPatch.cs
  NpcAdventure/Loader/ContentPacks/ContentPackProvider.cs
  NpcAdventure/Model/ContentPackData.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/Story/Scenario/QuestScenario.cs
  NpcAdventure/assets/Data/Events.pt-BR.json
  NpcAdventure/assets/Data/Quests.pt-BR.json
  NpcAdventure/assets/Dialogue/Abigail.pt-BR.json
  docs/modding/content-packs.md
Labels: bugfix, content, feature

#95 Change Marlon's invitation letter conditions for receive it
  NpcAdventure/NpcAdventureMod.cs
  NpcAdventure/Story/Scenario/AdventureBegins.cs
Labels: content, feature, testing

#100 Separate follow movement
  NpcAdventure/AI/Controller/FightController.cs
  NpcAdventure/AI/Controller/FollowController.cs
  NpcAdventure/AI/Controller/FollowJoystick.cs
  NpcAdventure/AI/Controller/PathFinder.cs
  NpcAdventure/NpcAdventure.csproj
Labels: feature, technical

#104 Spouse dialogues and some edits
  NpcAdventure/assets/Dialogue/Abigail.json
  NpcAdventure/assets/Dialogue/Alex.json
  NpcAdventure/assets/Dialogue/Elliott.json
  NpcAdventure/assets/Dialogue/Emily.json
  NpcAdventure/assets/Dialogue/Haley.json
  NpcAdventure/assets/Dialogue/Harvey.json
  NpcAdventure/assets/Dialogue/Leah.json
  NpcAdventure/assets/Dialogue/Maru.json
  NpcAdventure/assets/Dialogue/Penny.json
  NpcAdventure/assets/Dialogue/Sam.json
  NpcAdventure/assets/Dialogue/Sebastian.json
  NpcAdventure/assets/Dialogue/Shane.json
  NpcAdventure/assets/Strings/Strings.json
  NpcAdventure/assets/Strings/Strings.pt-BR.json
Labels: content

#106 Update CompanionDisplay.cs to work with Android
  NpcAdventure/HUD/CompanionDisplay.cs
  docs/guide/getting-started.md
Labels: bugfix, technical, testing, unplanned
