Repository purrplingcat/NpcAdventures, pull requests merged in 2020-04, with the labels that each got.

#123 More safe harmony patching
  NpcAdventure/Internal/Patching/GamePatcher.cs
  NpcAdventure/Internal/Patching/IPatch.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/NpcAdventureMod.cs
  NpcAdventure/Patches/CompanionSayHiPatch.cs
  NpcAdventure/Patches/GameLocationDrawPatch.cs
  NpcAdventure/Patches/GetCharacterPatch.cs
  NpcAdventure/Patches/MailBoxPatch.cs
  NpcAdventure/Patches/NpcCheckActionPatch.cs
  NpcAdventure/Patches/Patch.cs
  NpcAdventure/Patches/QuestPatch.cs
  NpcAdventure/Patches/SpouseReturnHomePatch.cs
Labels: enhancement, feature, technical

#128 Update Abigail.json
  NpcAdventure/assets/Dialogue/Abigail.json
Labels: content

#119 Forager skill for companions
  .gitignore
  NpcAdventure/AI/AI_StateMachine.cs
  NpcAdventure/AI/AI_StateMachine.doctor.cs
  NpcAdventure/AI/Controller/FightController.cs
  NpcAdventure/AI/Controller/FollowController.cs
  NpcAdventure/AI/Controller/FollowJoystick.cs
  NpcAdventure/AI/Controller/ForageController.cs
  NpcAdventure/HUD/CompanionDisplay.cs
  NpcAdventure/HUD/CompanionSkill.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/StateMachine/State/AvailableState.cs
  NpcAdventure/StateMachine/State/RecruitedState.cs
  NpcAdventure/Utils/DialogueHelper.cs
  NpcAdventure/assets/Data/CompanionDispositions.json
  NpcAdventure/assets/Data/IdleBehaviors.json
  NpcAdventure/assets/Dialogue/Leah.json
  NpcAdventure/assets/Strings/Strings.json
  README.md
  docs/changelog.md
  docs/modding/dialogues.md
Labels: content, feature

#129 Scared companion skill + some stuff
  NpcAdventure/AI/AI_StateMachine.cs
  NpcAdventure/AI/AI_StateMachine.doctor.cs
  NpcAdventure/AI/Controller/FightController.cs
  NpcAdventure/Commander.cs
  NpcAdventure/HUD/CompanionDisplay.cs
  NpcAdventure/HUD/CompanionSkill.cs
  NpcAdventure/Internal/Countdown.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/Utils/Helper.cs
  NpcAdventure/assets/Data/CompanionDispositions.json
  NpcAdventure/assets/Strings/Strings.json
  docs/changelog.md
Labels: content, feature, technical

#132 Refactored DialogueHelper to DialogueProvider
  NpcAdventure/AI/AI_StateMachine.cs
  NpcAdventure/AI/AI_StateMachine.doctor.cs
  NpcAdventure/AI/Controller/FightController.cs
  NpcAdventure/AI/Controller/FollowController.cs
  NpcAdventure/AI/Controller/ForageController.cs
  NpcAdventure/Dialogues/CompanionDialogue.cs
  NpcAdventure/Dialogues/DialogueProvider.cs
  NpcAdventure/Dialogues/VariousKeyGenerator.cs
  NpcAdventure/Driver/DialogueDriver.cs
  NpcAdventure/NpcAdventure.csproj
  NpcAdventure/StateMachine/CompanionStateMachine.cs
  NpcAdventure/StateMachine/State/AvailableState.cs
  NpcAdventure/StateMachine/State/RecruitedState.cs
  NpcAdventure/Utils/DialogueHelper.VariousKeyGenerator.cs
  docs/changelog.md
Labels: bugfix, enhancement, technical
